build: build ceph dependencies from source
With this commit we now build some of the packages ceph depends
on directly from source code. We use cmake and externalproject_add
to build the sources using a superbuild project approach. Not all
packages that are compiled into rook are built from source yet, but
enough are there to work around some of the issues we were ran into
with adding RGW to rook.

Specificaly, libcurl is now built from source and removes the
dependency on openldap and other unused protocols. Boost, zlib,
libblkid, and libuuid are now also built from source. More packages
will be added in the future to complete this approach.

The build container is now based on the yakkety release of ubuntu.

diff --git a/build/container/Dockerfile b/build/container/Dockerfile
--- a/build/container/Dockerfile
+++ b/build/container/Dockerfile
@@ -12,17 +12,19 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM ubuntu:xenial
+FROM ubuntu:yakkety
 MAINTAINER Bassam Tabbara <bassam.tabbara@quantum.com>
+
+WORKDIR /build
 
 #
 # install build tools, compilers and cross compilers for all supported platforms
 #
 
-RUN echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu xenial main universe restricted" > /etc/apt/sources.list &&\
-    echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu xenial-updates main universe restricted" >> /etc/apt/sources.list &&\
-    echo "deb [arch=arm64] http://ports.ubuntu.com/ xenial main universe restricted" >> /etc/apt/sources.list &&\
-    echo "deb [arch=arm64] http://ports.ubuntu.com/ xenial-updates main universe restricted" >> /etc/apt/sources.list &&\
+RUN echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu yakkety main universe restricted" > /etc/apt/sources.list &&\
+    echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu yakkety-updates main universe restricted" >> /etc/apt/sources.list &&\
+    echo "deb [arch=arm64] http://ports.ubuntu.com/ yakkety main universe restricted" >> /etc/apt/sources.list &&\
+    echo "deb [arch=arm64] http://ports.ubuntu.com/ yakkety-updates main universe restricted" >> /etc/apt/sources.list &&\
     dpkg --add-architecture arm64 && \
     apt-get update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
@@ -42,7 +44,8 @@ RUN echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu xenial main universe
         mingw-w64 \
         patch \
         python \
-        python-dev \
+        libpython-dev:amd64 \
+        libpython-dev:arm64 \
         rsync \
         runit \
         sudo \
@@ -70,85 +73,10 @@ RUN ACBUILD_VERSION=0.4.0 && \
     curl -fsSLO https://github.com/containers/build/releases/download/v${ACBUILD_VERSION}/acbuild-v${ACBUILD_VERSION}.tar.gz && \
     tar -C /usr/local/bin --strip-components=1 -xzf acbuild-v${ACBUILD_VERSION}.tar.gz && \
     rm -f acbuild-v${ACBUILD_VERSION}.tar.gz && \
-    DOCKER2ACI_VERSION=0.12.3 && \
+    DOCKER2ACI_VERSION=0.14.0 && \
     curl -fsSLO https://github.com/appc/docker2aci/releases/download/v${DOCKER2ACI_VERSION}/docker2aci-v${DOCKER2ACI_VERSION}.tar.gz && \
     tar -C /usr/local/bin --strip-components=1 -xzf docker2aci-v${DOCKER2ACI_VERSION}.tar.gz && \
     rm -f docker2aci-v${DOCKER2ACI_VERSION}.tar.gz
-
-#
-# install multi-arch packages needed to build ceph
-#
-RUN for a in amd64 arm64; do \
-    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-overwrite" install -yq --no-install-recommends \
-    libatomic-ops-dev:${a} \
-    libblkid-dev:${a} \
-    libboost-date-time-dev:${a} \
-    libboost-dev:${a} \
-    libboost-iostreams-dev:${a} \
-    libboost-program-options-dev:${a} \
-    libboost-random-dev:${a} \
-    libboost-regex-dev:${a} \
-    libboost-system-dev:${a} \
-    libboost-thread-dev:${a} \
-    libcurl4-openssl-dev:${a} \
-    libexpat1-dev:${a} \
-    libkeyutils-dev:${a} \
-    libldap2-dev:${a} \
-    libsnappy-dev:${a} \
-    libssl-dev:${a} \
-    libudev-dev:${a} \
-    ; done
-
-# Some of the packages we need for ceph are either not available in xenial or dont support multi-arch.
-# Hack'em to install in a multi-arch way. Hopefully these will get fixed upstream soon.
-# Bugs opened here https://bugs.launchpad.net/~bassamtabbara
-RUN curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++-dev_5.6.4-3_amd64.deb && \
-    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++-dev_5.6.4-3_arm64.deb && \
-    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++6_5.6.4-3_amd64.deb && \
-    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++6_5.6.4-3_arm64.deb && \
-    curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/libf/libfcgi/libfcgi-dev_2.4.0-8.4_amd64.deb && \
-    curl -fsSLO http://ports.ubuntu.com/pool/main/libf/libfcgi/libfcgi-dev_2.4.0-8.4_arm64.deb && \
-    curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/libf/libfcgi/libfcgi0ldbl_2.4.0-8.4_amd64.deb && \
-    curl -fsSLO http://ports.ubuntu.com/pool/main/libf/libfcgi/libfcgi0ldbl_2.4.0-8.4_arm64.deb && \
-    for a in amd64 arm64; do \
-        apt-get download libaio-dev:${a} 2> /dev/null && \
-        apt-get download libaio1:${a} 2> /dev/null && \
-        apt-get download libjemalloc-dev:${a} 2> /dev/null && \
-        apt-get download libjemalloc1:${a} 2> /dev/null && \
-        apt-get download libgoogle-perftools4:${a} 2> /dev/null && \
-        apt-get download libgoogle-perftools-dev:${a} 2> /dev/null && \
-        apt-get download libtcmalloc-minimal4:${a} 2> /dev/null && \
-        apt-get download libunwind-dev:${a} 2> /dev/null && \
-        apt-get download libunwind8-dev:${a} 2> /dev/null && \
-        apt-get download libunwind8:${a} 2> /dev/null && \
-        apt-get download liblzma5:${a} 2> /dev/null; \
-        apt-get download liblzma-dev:${a} 2> /dev/null; \
-    done
-
-RUN for d in *.deb; do \
-        dpkg-deb -R ${d} root && \
-        arch=$(cat root/DEBIAN/control | awk '/Architecture/ {printf "%s", $2}') && \
-        case ${arch} in amd64) triple=x86_64-linux-gnu ;; arm64) triple=aarch64-linux-gnu ;; esac && \
-        if test ! -d root/usr/lib/${triple} -a ! -d root/lib/${triple}; then \
-            if test -d root/usr/lib; then \
-                echo HACK: moving root/usr/lib for package ${d} && \
-                mv root/usr/lib root/usr/lib.rename && \
-                mkdir -p root/usr/lib && \
-                mv root/usr/lib.rename root/usr/lib/${triple}; \
-            fi; \
-        fi && \
-        if ! grep 'Multi-Arch' root/DEBIAN/control >/dev/null; then \
-            echo HACK: setting Multi-Arch: same for package ${d}; \
-            sed -i '/^Architecture:.*$/a Multi-Arch: same' root/DEBIAN/control; \
-        fi && \
-        dpkg-deb -b root ${d} && \
-        rm -fr root; \
-    done && \
-    dpkg -i --force-overwrite *.deb && \
-    rm -f *.deb
-
-# cleanup apt-get
-RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 # install go-lang
 RUN GO_VERSION=1.7.3 && \
@@ -157,13 +85,16 @@ RUN GO_VERSION=1.7.3 && \
     echo "${GO_HASH}  golang.tar.gz" | sha256sum -c - && \
     tar -C /usr/local -xzf golang.tar.gz && \
     rm golang.tar.gz
+
 ENV PATH /usr/local/go/bin:$PATH
 
+#
 # precompile the go standard library for all supported platforms and configurations
 # there are three configurations that we compile for:
 #    - default: CGO_ENABLED=1, defaults tags
 #    - netgo: CGO_ENABLED=1, enable pure go DNS resolver
 #    - nocgo: CGO_ENABLED=0, defaults tags, pure Go resolver is the default
+#
 RUN \
     CGO_ENABLED=1 GOOS=darwin  GOARCH=amd64 CC=o64-clang              go install -a std && \
     CGO_ENABLED=1 GOOS=darwin  GOARCH=amd64 CC=o64-clang              go install -installsuffix netgo -tags netgo -a std && \
@@ -182,7 +113,83 @@ RUN \
     \
     CGO_ENABLED=1 GOOS=linux   GOARCH=amd64 CC=x86_64-linux-gnu-gcc   go install -installsuffix race -a std
 
-WORKDIR /build
+#
+# build packages we need for ceph from source on all supported platforms
+#
+
+COPY external /build/external/
+
+RUN set -e;\
+    for a in linux_amd64 linux_arm64; do \
+      cmake -Hexternal -Bexternal/build/${a} -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_TOOLCHAIN_FILE=`pwd`/external/toolchain/gcc.${a}.cmake ;\
+      cmake --build external/build/${a} --target install;\
+    done ;\
+    rm -fr external
+
+RUN set -e;\
+    for a in amd64 arm64; do \
+    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-overwrite" install -yq --no-install-recommends \
+    libatomic-ops-dev:${a} \
+    libexpat1-dev:${a} \
+    libkeyutils-dev:${a} \
+    libsnappy-dev:${a} \
+    libssl-dev:${a} \
+    libudev-dev:${a} \
+    ; done
+
+# Some of the packages we need for ceph are either not available in yakkety or dont support multi-arch.
+# Hack'em to install in a multi-arch way. Hopefully these will get fixed upstream soon.
+# Bugs opened here https://bugs.launchpad.net/~bassamtabbara
+RUN set -e;\
+    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++-dev_5.6.4-3_amd64.deb ;\
+    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++-dev_5.6.4-3_arm64.deb ;\
+    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++6_5.6.4-3_amd64.deb ;\
+    curl -fsSLO http://http.us.debian.org/debian/pool/main/libc/libcrypto++/libcrypto++6_5.6.4-3_arm64.deb ;\
+    curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/libf/libfcgi/libfcgi-dev_2.4.0-8.4_amd64.deb ;\
+    curl -fsSLO http://ports.ubuntu.com/pool/main/libf/libfcgi/libfcgi-dev_2.4.0-8.4_arm64.deb ;\
+    curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/libf/libfcgi/libfcgi0ldbl_2.4.0-8.4_amd64.deb ;\
+    curl -fsSLO http://ports.ubuntu.com/pool/main/libf/libfcgi/libfcgi0ldbl_2.4.0-8.4_arm64.deb ;\
+    for a in amd64 arm64; do \
+        apt-get download libaio-dev:${a} 2> /dev/null ;\
+        apt-get download libaio1:${a} 2> /dev/null ;\
+        apt-get download libjemalloc-dev:${a} 2> /dev/null ;\
+        apt-get download libjemalloc1:${a} 2> /dev/null ;\
+        apt-get download libgoogle-perftools4:${a} 2> /dev/null ;\
+        apt-get download libgoogle-perftools-dev:${a} 2> /dev/null ;\
+        apt-get download libtcmalloc-minimal4:${a} 2> /dev/null ;\
+        apt-get download libunwind-dev:${a} 2> /dev/null ;\
+        apt-get download libunwind8-dev:${a} 2> /dev/null ;\
+        apt-get download libunwind8:${a} 2> /dev/null ;\
+        apt-get download liblzma5:${a} 2> /dev/null; \
+        apt-get download liblzma-dev:${a} 2> /dev/null; \
+    done
+
+RUN set -e; \
+    for d in *.deb; do \
+        dpkg-deb -R ${d} root ;\
+        arch=$(cat root/DEBIAN/control | awk '/Architecture/ {printf "%s", $2}') ;\
+        case ${arch} in amd64) triple=x86_64-linux-gnu ;; arm64) triple=aarch64-linux-gnu ;; esac ;\
+        if test ! -d root/usr/lib/${triple} -a ! -d root/lib/${triple}; then \
+            if test -d root/usr/lib; then \
+                echo HACK: moving root/usr/lib for package ${d} ;\
+                mv root/usr/lib root/usr/lib.rename ;\
+                mkdir -p root/usr/lib ;\
+                mv root/usr/lib.rename root/usr/lib/${triple}; \
+            fi; \
+        fi ;\
+        if ! grep 'Multi-Arch' root/DEBIAN/control >/dev/null; then \
+            echo HACK: setting Multi-Arch: same for package ${d}; \
+            sed -i '/^Architecture:.*$/a Multi-Arch: same' root/DEBIAN/control; \
+        fi ;\
+        dpkg-deb -b root ${d} ;\
+        rm -fr root; \
+    done ;\
+    dpkg -i --force-overwrite *.deb ;\
+    rm -f *.deb
+
+# cleanup apt-get
+RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
 COPY entrypoint.sh rsyncd.sh /build/
 
 ENTRYPOINT [ "/build/entrypoint.sh" ]
